USE [master]
GO
/****** Object:  Database [Rourie]    Script Date: 28.09.2020 01:38:42 ******/
CREATE DATABASE [Rourie]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Rourie', FILENAME = N'C:\Users\ozdemiey\Rourie.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Rourie_log', FILENAME = N'C:\Users\ozdemiey\Rourie_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Rourie] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Rourie].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Rourie] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Rourie] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Rourie] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Rourie] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Rourie] SET ARITHABORT OFF 
GO
ALTER DATABASE [Rourie] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Rourie] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Rourie] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Rourie] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Rourie] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Rourie] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Rourie] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Rourie] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Rourie] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Rourie] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Rourie] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Rourie] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Rourie] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Rourie] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Rourie] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Rourie] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Rourie] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Rourie] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Rourie] SET  MULTI_USER 
GO
ALTER DATABASE [Rourie] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Rourie] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Rourie] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Rourie] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Rourie] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Rourie] SET QUERY_STORE = OFF
GO
USE [Rourie]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Rourie]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 28.09.2020 01:38:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Company]    Script Date: 28.09.2020 01:38:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Company](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Address] [nvarchar](500) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contact]    Script Date: 28.09.2020 01:38:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contact](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[JobTitle] [nvarchar](250) NOT NULL,
	[Email] [nvarchar](250) NOT NULL,
	[MobileNumber] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 28.09.2020 01:38:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](60) NULL,
	[Password] [nvarchar](250) NOT NULL,
	[UserType] [int] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20200927094130_V1', N'3.1.8')
GO
SET IDENTITY_INSERT [dbo].[User] ON 
GO
INSERT [dbo].[User] ([Id], [UserName], [Password], [UserType]) VALUES (1, N'admin', N'admin123', 1)
GO
INSERT [dbo].[User] ([Id], [UserName], [Password], [UserType]) VALUES (2, N'testuser', N'testuser123', 0)
GO
SET IDENTITY_INSERT [dbo].[User] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Company_Name]    Script Date: 28.09.2020 01:38:43 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Company_Name] ON [dbo].[Company]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Contact_CompanyId]    Script Date: 28.09.2020 01:38:43 ******/
CREATE NONCLUSTERED INDEX [IX_Contact_CompanyId] ON [dbo].[Contact]
(
	[CompanyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Contact_Email]    Script Date: 28.09.2020 01:38:43 ******/
CREATE NONCLUSTERED INDEX [IX_Contact_Email] ON [dbo].[Contact]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_User_UserName]    Script Date: 28.09.2020 01:38:43 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_User_UserName] ON [dbo].[User]
(
	[UserName] ASC
)
WHERE ([UserName] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Contact]  WITH CHECK ADD  CONSTRAINT [FK_Contact_Company_CompanyId] FOREIGN KEY([CompanyId])
REFERENCES [dbo].[Company] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Contact] CHECK CONSTRAINT [FK_Contact_Company_CompanyId]
GO
USE [master]
GO
ALTER DATABASE [Rourie] SET  READ_WRITE 
GO
